# Find the armstrong number using while

# i = 1
# n = int(input("enter any number : "))
# k = n
# m = n
# sum = 0
# pw = 0

# while n > 0:
#     n = n // 10
#     pw += 1
  
# while k > 0:
#     r = n % 10
#     sum = sum + r ** pw


# -------------------------------------------------------------------------------

# Fibonacci series is generated by adding the previous two numbers, starting from 0 and 1.
# Fibonacci is a sequence where each number is the sum of the previous two numbers.

# Find the armstrong number using for loop 
# An Armstrong number is a number that is equal to the sum of its digits raised to the power of the number of digits.

# 153  Output = 153


# n = int(input("enter any number : "))
# length = len(str(n))

# result = 0
# for x in range(0,length):
#     # print(x)
#     r = n % 10
#     result += r ** length 
#     n = n // 10
# print(result)

n = int(input("enter any number : "))
length = len(str(n))
temp = n
sum1 = 0

while temp > 0:
    r = temp % 10
    temp = temp // 10
    sum1 = sum1 *10 + r
    # print(sum1)
    # sum = sum + r ** length
if(sum1 == n):
    print("palandrome")
else:
    print("not palandrome")
    
# print(sum)